[package]
name = "codegen-luau"
version = "0.7.0"
edition = "2021"

[dependencies]
wasmparser = "0.86.0"

[dependencies.wasm-ast]
path = "../../wasm-ast"

[features]
default = ["vector"]
vector = []

[[bin]]
name = "wasm2luau"
